[package]
name = "cyclonedds-rs"
version = "0.12.0"
description = "Safe Rust bindings for cyclonedds"
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
cdr = "0.2.4"
cyclonedds-sys.workspace = true
futures-util = "0.3.33"
murmur3 = "0.5.2"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tracing = "0.1.44"
uuid = "1.24.0"

[features]
shm = ["cyclonedds-sys/shm"]
default = ["shm"]

[dev-dependencies]
anyhow = "1"
cdds_derive.workspace = true
test-log = { version = "0.2.21", default-features = false, features = ["trace"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.19"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
