[package]
name = "cdds_derive"
version = "0.3.0"
description = "Derive macros for cyclonedds-rs"
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lib]
proc-macro = true
