name: PR Check
on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-actions:
    uses: ./.github/workflows/actions-lint.yml

  tests:
    uses: ./.github/workflows/test.yml
